# Generated by Django 4.1 on 2022-08-24 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Familia', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Familia',
            new_name='Familiar',
        ),
    ]
